apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 9464
      targetPort: 9464
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Release.Name }}
