replicaCount: 2
image:
  repository: panjek26/go-service
  tag: fd966fd
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: go-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
env:
  - name: DB_HOST
    value: postgres.default.svc.cluster.local
  - name: DB_PORT
    value: '5432'
  - name: DB_USER
    value: youruser
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: password
  - name: DB_NAME
    value: yourdb
  - name: REDIS_HOST
    value: redis.default.svc.cluster.local
  - name: REDIS_PORT
    value: '6379'
